# Generated by Django 4.0.5 on 2022-06-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regular_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(max_length=10)),
                ('school', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=20)),
                ('github', models.CharField(max_length=30)),
                ('active_coding_platform', models.CharField(max_length=20)),
            ],
        ),
    ]
