# Generated by Django 4.0.5 on 2022-06-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular_user',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
