# Generated by Django 4.0.5 on 2022-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_regular_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regular_user',
            old_name='active_coding_platform',
            new_name='active_coding_platfor',
        ),
        migrations.AlterField(
            model_name='regular_user',
            name='phone_number',
            field=models.IntegerField(blank=True, help_text='Contact phone number'),
        ),
    ]
