# Generated by Django 4.0.5 on 2022-07-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_active_coding_platform_regular_user_active_coding_platfor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regular_user',
            name='profession',
        ),
    ]
